### PR TITLE
Issues/259 specific scenario test command

### PR DESCRIPTION
**Pull request by miguel1770**
```
make fixture_tests ARGS="--scenarios=multi_msg_tx,double_empty"
```
This PR is to add flag to test specific scenarios instead of all.
This closes #28

### CODE REVIEW

**Review by antstalepresh — COMMENTED** [review]
Can you add README for changes made?
There should be a section that describes the meaning of flags.

**Comment by miguel1770** [comment]
> Can you add README for changes made?
> There should be a section that describes the meaning of flags.

OK

**Comment by antstalepresh** [comment]
Also you need to create a PR for pylons to and possibly LOUD for sdk changes.

**Comment by antstalepresh** [comment]
Overall it looks good

**Pull request merged**
